#!/bin/bash

# Add all files to the staging area
git add .

echo "Message:"
read COMMIT_MESSAGE

# Commit the changes with the user's message
git commit -m "$COMMIT_MESSAGE"

BRANCH_NAME="master"

# Push the changes to the remote repository
git push origin $BRANCH_NAME

